{{- if .Values.create.app_resources -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "service.name" . }}
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector: {{ include "common.labels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.container.port }}
{{- end -}}
