apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ template "tekton.event-listener.name" . }}
  namespace: {{ .Values.tekton.namespace }}
spec:
  serviceAccountName: tekton-event-listener-sa
  triggers:
    - interceptors:
        - github:
            secretRef:
              secretName: {{ template "tekton.github-token-secret.name" . }}
              secretKey: token
            eventTypes:
              - push
        - cel:
            filter: "header.match('X-GitHub-Event', 'pull_request')"
            overlays:
              - key: extensions.branch
                expression: "body.ref.split('/')[2]"
              - key: extensions.head_short_sha
                expression: "body.pull_request.head.id.truncate(7)"
      bindings:
        - ref: github-binding
      template:
        ref: {{ template "tekton.tt.github.push.name" . }}
