{{- if .Values.create.tektonResources -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "tekton.app-secret.name" . }}
  namespace: {{ .Values.tekton.namespace }}
type: Opaque
stringData:
  env: {{ .Values.environment }}
  env-prefix: {{ .Values.envPrefix }}
  app-name: {{ .Values.appName }}
  app-slug-name: {{ .Values.appSlugName }}
  product-name: {{ .Values.productName }}
  github-token: {{ .Values.secretData.githubToken }}
  ecr-repo-url: {{ .Values.secretData.ecrRepoUrl }}
  ssh-deploy-key: {{ .Values.secretData.sshDeployKey | toYaml | indent 1 }}
{{- end -}}
