{{- if .Values.platform.createPlatformResources -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.platform.secretName }}
  namespace: {{ .Values.platform.namespace }}
type: Opaque
stringData:
  svc-json: {{ .Values.secretData.svcJson }}
  env: {{ .Values.environment }}
  env-prefix: {{ .Values.envPrefix }}
  app-name: {{ .Values.appName }}
  app-port: {{ .Values.appPort }}
  app-iam-role-arn: {{ .Values.appIAMRoleARN }}
  app-slug-name: {{ .Values.appSlugName }}
  product-name: {{ .Values.productName }}
  github-token: {{ .Values.secretData.githubToken }}
  ecr-repo-url: {{ .Values.secretData.ecrRepoUrl }}
  ssh-deploy-key: {{ .Values.secretData.sshDeployKey | toYaml | indent 1 }}
  helm-chart-github-url: {{ .Values.platform.helmChartGithubUrl }}
{{- end -}}
