{{- if .Values.create.tektonResources -}}
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: {{ template "tekton.event-listener.name" . }}
  namespace: {{ .Values.tekton.namespace }}
spec:
  serviceAccountName: {{ template "tekton.sa.name" . }}
  triggers:
    - interceptors:
        - github:
            secretRef:
              secretName: {{ template "tekton.app-secret.name" . }}
              secretKey: github-token
            eventTypes:
              - push
        - cel:
            overlays:
              - key: branch
                expression: "body.ref.split('/')[2]"
              - key: head_short_sha
                expression: "body.head_commit.id.truncate(7)"
      bindings:
        - ref: github-binding
      template:
        ref: {{ template "tekton.tt.github.push.name" . }}
{{- end -}}
