{{- if .Values.platform.createTektonResources -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "tekton.ingress.name" . }}
  namespace: {{ .Values.platform.namespace }}
  labels: {{ include "common.labels" . | nindent 4 }}
  annotations: {{ (toYaml .Values.tekton.ingress.annotations) | nindent 4 }}
spec:
  rules:
    - host: {{ .Values.tekton.ingress.domain }}
      http:
        paths:
        - path: "{{ .Values.tekton.ingress.pathPrefix }}"
          pathType: Exact
          backend:
            service:
              name: {{ template "tekton.event-listener-svc.name" . }}
              port:
                number: {{ .Values.tekton.ingress.port }}
{{- end -}}
