{{- if .Values.platform.createTektonResources -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "tekton.sa.name" . }}
  namespace: {{ .Values.platform.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.platform.appPipelineIAMRoleARN }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "common.name" . }}-tekton-cr
rules:
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["clustertriggerbindings", "clusterinterceptors"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "common.name" . }}-tekton-crb
subjects:
  - kind: ServiceAccount
    name: {{ template "tekton.sa.name" . }}
    namespace: {{ .Values.platform.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "common.name" . }}-tekton-cr
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "common.name" . }}-tekton-platform-ro
  namespace: {{ .Values.platform.namespace }}
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["triggers.tekton.dev"]
    resources:
      ["eventlisteners", "triggerbindings", "triggertemplates", "triggers", "interceptors"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch", "impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.name" . }}-tekton-platform-rb
  namespace: {{ .Values.platform.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "tekton.sa.name" . }}
    namespace: {{ .Values.platform.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "common.name" . }}-tekton-platform-ro
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "common.name" . }}-tekton-app-ro
  namespace: {{ .Values.namespace }}
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "common.name" . }}-tekton-app-rb
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ template "tekton.sa.name" . }}
    namespace: {{ .Values.platform.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "common.name" . }}-tekton-app-ro
{{- end -}}
