{{- if .Values.platform.createPlatformResources -}}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
  namespace: {{ .Values.platform.namespace }}
spec:
  params:
    - name: branch
      value: $(extensions.branch)
    - name: git_short_sha
      value: $(extensions.head_short_sha)
    - name: owner_and_repo # owner/repo_name
      value: $(extensions.owner_and_repo)
    - name: git_https_url
      value: $(body.repository.clone_url)
{{- end -}}
