{{- if .Values.platform.createTektonResources -}}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
  namespace: {{ .Values.platform.namespace }}
spec:
  params:
    - name: branch
      value: $(extensions.branch)
    - name: git_short_sha
      value: $(extensions.head_short_sha)
    - name: repo_full_name # owner/repo_name
      value: $(body.repository.full_name)
{{- end -}}
