{{- if .Values.create.tektonResources -}}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: github-binding
  namespace: {{ .Values.tekton.namespace }}
spec:
  params:
    - name: branch
      value: $(extensions.branch)
    - name: gitShortSha
      value: $(extensions.head_short_sha)
    - name: repoFullName # owner/repo_name
      value: $(body.repository.full_name)
{{- end -}}
