{{- if .Values.platform.createTektonResources -}}
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: {{ template "tekton.tt.github.push.name" . }}
  namespace: {{ .Values.platform.namespace }}
  annotations:
    triggers.tekton.dev/old-escape-quotes: "true"
spec:
  params:
    - name: branch
      description: Name of the git branch
    - name: owner_and_repo
      description: Github repository owner and repo name formatted
    - name: git_short_sha
      description: Github head commit id short sha
    - name: git_https_url
      description: Git https url to clone resources from

  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: {{ template "tekton.pipelinerun.name-prefix" . }}
        namespace: {{ .Values.platform.namespace }}
      spec:
        serviceAccountName: {{ template "tekton.sa.name" . }}
        pipelineRef:
          name: {{ template "tekton.push.pipeline.name" . }}
        podTemplate:
          securityContext:
            fsGroup: 0
        workspaces:
          - name: shared
            volumeClaimTemplate:
              spec:
                storageClassName: {{ .Values.platform.pipelineStorageClass }}
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
        params:
          - name: branch
            value: $(tt.params.branch)
          - name: owner_and_repo
            value: $(tt.params.owner_and_repo)
          - name: git_short_sha
            value: $(tt.params.git_short_sha)
          - name: git_https_url
            value: $(tt.params.git_https_url)
{{- end -}}
